# Generated by Django 2.0.3 on 2018-04-03 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_clue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_clue_number', to='sales_department.Contractclue', verbose_name='线索编号'),
        ),
    ]
